### PR TITLE
Allow arrays of middleware as routes

### PR DESCRIPTION
**Pull request by bergie**
In Express you can either provide a single middleware function as a route, or an array of middlewares. This adds support for middleware arrays.

### CODE REVIEW

**Comment by olalonde** [comment]
Thanks :+1:

**Comment by bergie** [comment]
@olalonde thanks for merging! Could you make a new NPM release?

**Comment by bergie** [comment]
@olalonde ping! can you release this to NPM?

**Comment by olalonde** [comment]
@bergie oops, would you like to maintain this module? I can add you as an owner on npm. I no longer use it so it would help :)

**Comment by bergie** [comment]
Sure, that works!

**Comment by olalonde** [comment]
Thanks. Added you as an owner on npm and a collaborator on Github.

**Pull request merged**
